### ISSUE TITLE
botbuilder has no exported member ConsoleLogger

### ISSUE THREAD

**Issue by navzam** [cmayomsft/promptly-js#1]
Running `tsc` on any of the samples gives this error:

```
src/app.ts(2,15): error TS2305: Module '"<path>/promptly-js/samples/alarmbot-ts/node_modules/botbuilder/lib/botbuilder"' has no exported member 'ConsoleLogger'.
```

It looks like `botbuilder` recently removed `ConsoleLogger`.

**Comment by cmayomsft** [comment]
Y, cleaning up the samples now for M2. Will reply back when it's in so you can check it out.

**Comment by navzam** [comment]
Closing, no longer relevant
